### ISSUE TITLE
maxPingTimeouts upper bounds

### ISSUE THREAD

**Issue by magx2** [seime/openhab-esphome#24]
Hey,

Can you remove `max="600"` for parameter `maxPingTimeouts`? I would like to set it to `3'000`, but this upper limit is preventing me from doing it.

https://github.com/seime/openhab-esphome/blob/178b362048e3c8a1a10ddc1be7946efdda7f2b18/src/main/resources/OH-INF/thing/thing-types.xml#L52

My use case is: I'm using `deep_sleep: 50 min` in my ESP and I want thing to try to connect with ESP 3k times (with 1 sec of ping interval)

**Comment by seime** [comment]
Fixed

**Comment by magx2** [comment]
Thanks

niedz., 21 lip 2024, 20:36 użytkownik Arne Seime ***@***.***>
napisał:

**Comment by seime** [comment]
I removed the wrong limit, but both `pingInterval` and `maxPingTimeouts` should be freely configurable now

**Comment by magx2** [comment]
Thanks

pon., 22 lip 2024, 13:14 użytkownik Arne Seime ***@***.***>
napisał:
