### ISSUE TITLE
Support for `deep_sleep`

### ISSUE THREAD

**Issue by magx2** [seime/openhab-esphome#25]
Hey,

I'm using your library to connect with my ESP that has an eink screen. This device runs on a battery, so I need to use deep sleep to extend its battery life. My use case looks like this:

1. Turn on for 1 min
2. Get data from OH
3. Turn off for 45 min
4. Repeat

I see that this use case is not currently supported by your software. Are you able to add it?

**Comment by seime** [comment]
I have not dug into deep sleep yet, so please enligthen me; what needs to be added to the binding?

**Comment by magx2** [comment]
I would imagine this:

1. add bool config property called `deepSleep` - if it's enabled the the rest of the algorithm applies
2. add int config property called `deepSleepReconnect` - this is value for [scheduleReconnect](https://github.com/seime/openhab-esphome/blob/master/src/main/java/no/seime/openhab/binding/esphome/internal/handler/ESPHomeHandler.java#L185) (right now it's hardcoed 40 secs)
3. add int config property called `deepSleepMaxRetries` - after how many reconnects the device should be considered offline
4. do **not** make the thing offline until hits `deepSleepMaxRetries`. Also do not log in `WARN` `"[{}] Error initial connection"` (I had to turn off logs for this class, because it was killing me)

So my use case would look like this:

```
deepSleep=true
deepSleepReconnect=10 // try every 10 secs to connect to device
deepSleepMaxRetries=270 // 45 min / 10 secs = 270 - my device turns on every 45 mins so this should work just fine
```

OH would try to connect to ESP every 10 secs and after 270 attempts (not earlier) it would put my thing as offline

before reaching 270 attempts:
![obraz](https://github.com/user-attachments/assets/2b4eb614-ca99-41f2-a420-fe3c9b7c2f1f)

after 270 attempts:
![obraz](https://github.com/user-attachments/assets/aa3f3d87-1f49-460e-a0ab-744216735738)

**Comment by magx2** [comment]
And of course if it will establish connection with ESP at least once it will be online all the time (unless 270 attempts threshold will be hit)

**Comment by seime** [comment]
Ok, then I understand what you mean. I'll take a look - or feel free to create a PR :)

**Comment by magx2** [comment]
Any luck?

**Comment by seime** [comment]
Just a quick look so far, but regular life got in between.

If you'll create a PR I'll try to prioritize reviewing and merging it

**Comment by seime** [comment]
Fixed via https://github.com/seime/openhab-esphome/pull/33
