### ISSUE TITLE
Missing Climate Features 

### ISSUE THREAD

**Issue by mjcumming** [seime/openhab-esphome#27]
've been playing around with the ESPHome binding and noticed it's missing support for a couple of climate features:

Humidity:

No channels for current_humidity or target_humidity
handleState() doesn't process humidity updates from ClimateStateResponse

Two-Point Target Temperature:

Binding doesn't create separate channels for target_temperature_low and target_temperature_high when supports_two_point_target_temperature is true
handleState() doesn't update these values separately

These features are supported in the ESPHome API (as per the proto files), but the binding doesn't seem to implement them yet. 

Adding support for these would make the binding more compatible with a wider range of climate devices.
Let me know if you need any more info or if you'd like help testing when these features are added!

**Comment by seime** [comment]
Hi @mjcumming,

I've added the new humidity channels plus support for high/low target temperature. 

Please give the latest version a spin; my climate devices supports neither of the features so I cannot tell for sure if it works as intented or not.

**Comment by mjcumming** [comment]
Thank you. Working so far!
