### ISSUE TITLE
Discovered things show a string REMOVEMEWHENADDING which cannot be removed before adding

### ISSUE THREAD

**Issue by schmidmuc** [seime/openhab-esphome#28]
Discovered things show a string REMOVEMEWHENADDING which cannot be removed before adding and therefore remains in the thing configuration.

![image](https://github.com/user-attachments/assets/f4fb346c-47b1-4d0b-aa54-b3cc566aeac1)

Workaround is to add the device manually where you can manually define the id.

**Comment by seime** [comment]
That is an openhab limitation and has nothing to do with this binding. Please file an issue at the openhab-webui repo.

If you add the thing from the inbox page (opposed from the discovery page) you are presented with an option to use a custom thingid.

![CleanShot 2024-08-25 at 09 05 56@2x](https://github.com/user-attachments/assets/05281d37-1233-4d19-922f-91c422c32ad8)
