### ISSUE TITLE
UVI unit not supported

### ISSUE THREAD

**Issue by marcusb** [seime/openhab-esphome#30]
I have a device with a LTR-390 ambient light and UV sensor, and the binding it emits this warning every few seconds:
```
2024-09-01 21:44:17.986 [WARN ] [ernal.message.AbstractMessageHandler] - Unit 'UVI' unknown to openHAB, returning DecimalType for state '0.0' on channel 'esphome:device:mtr1:ltr390_uv_index'
```
I would guess it should be treated as a Number.

**Comment by seime** [comment]
`UVI` is not listed as a valid unit here: (which is linked from esphome doc):  https://www.home-assistant.io/integrations/sensor/#device-class

Solution: In your esphome config, set `device_class` and `unit` to valid values. 
Ie setting `device_class` to `generic_number` and `unit` to `None` or empty would treat the values as pure numbers (`Number`) without any quanity information.

**Comment by marcusb** [comment]
Ok but this device ([Apollo MTR-1](https://apolloautomation.com/products/mtr-1)) is built for HomeAssistant so it definitely works there. Perhaps it's sensible to default to `Number` for unknown units?

It would also be helpful to only warn on this once, not every few seconds.

**Comment by seime** [comment]
Could you give the latest version a spin @marcusb ?

**Comment by marcusb** [comment]
Yes, appears to be fixed. Thank you!
