### ISSUE TITLE
lock // feature request

### ISSUE THREAD

**Issue by dasebi** [seime/openhab-esphome#31]
Hi guys, 

Thanks for the great work. I would like to make a feature request to support esphome locks.
I'm using this https://github.com/digaus/esphome-components-eqiva to drive a equiva door lock in my basement.  
It would be amazing if the door lock would be switchable from openhab. 

many thanks. 
Sebastian

**Comment by seime** [comment]
Adding lock support should be fairly doable, feel free to create a PR

**Comment by seime** [comment]
Added some preliminary support in latest release, **untested**

https://buymeacoffee.com/arnes

**Comment by dasebi** [comment]
Just wanted to let you know that it works like a charm! Thanks for the quick help on adding the lock feature.
