### ISSUE TITLE
Not Compatible with OH 4.3.0

### ISSUE THREAD

**Issue by cd-tronic** [seime/openhab-esphome#34]
It looks like openhab-esphome is not compatible with OH 4.3.0. 
I always get an Error: "Error while starting Bundle ...."
I tried the latest two snapshot versions.

**Comment by seime** [comment]
Thanks for the info, I'll take a look tonight

**Comment by seime** [comment]
It currently requires the bluetooth binding to be installed as well.

**Comment by seime** [comment]
Should be fixed in latest version (no bluetooth binding requirements) - can you verify?

**Comment by cd-tronic** [comment]
I installed Bluetoothbinding yesterday for testingpurpose and ESPHome Binding worked than.
I now uninstalled both bindings and reinstalled ESPHome. Everything works like expected!

Thank you very much for the fast fix and your work on this Binding!
