### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by jimtng** [seime/openhab-esphome#4]
Every time I built this, I got the following error:
```
[ERROR] Could not find resource '.../openhab-esphome/${basedirRoot}/tools/static-code-analysis/spotbugs/suppressions.xml'. -> [Help 1]
```

My build command:
```
$ mvn spotless:apply install
```

**Comment by seime** [comment]
Fixed.

**Comment by seime** [comment]
(fixed by disabling the sat plugin as I have not had time to figure out why it requires a specific feature name pattern)
